name: Cypress Tests

on: [push]

# ADICIONE ESTE BLOCO DE PERMISSÕES
permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_username: ${{ secrets.SAUCE_USERNAME }}
          CYPRESS_password: ${{ secrets.SAUCE_PASSWORD }}
